### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by garethsaxby**
Don't forget, you're here forever.

### CODE REVIEW

**Comment by danbosscher** [comment]
Looks good to me. Do you have an approved change control number?

**Comment by garethsaxby** [comment]
This issue was submitted as change ID10T to the eCAB in line with emergency change process.
Parties responsible for the late submission have been given 50 lashes, as per company policy.

**Comment by danbosscher** [comment]
Amount of lashes is too low but we'll proceed anyway. #devops

**Comment by garethsaxby** [comment]
Also +1

**Pull request merged**
